[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # Specify a Node.js version if your project requires it, common for Vite/React
  # NPM_VERSION = "8" # Optionally specify npm version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200