CREATE TABLE public.invitation_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    is_used BOOLEAN DEFAULT FALSE NOT NULL,
    used_by UUID REFERENCES auth.users(id),
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMPTZ,
    -- 어떤 플랜으로 변경할지, 얼마나 오랫동안 유지할지에 대한 정보 추가
    plan_type TEXT DEFAULT 'pro' NOT NULL,
    duration_days INTEGER DEFAULT 365
);

ALTER TABLE public.invitation_codes ENABLE ROW LEVEL SECURITY;

-- 서비스 관리자만 모든 코드를 관리할 수 있도록 허용
CREATE POLICY "Allow admin to manage invitation codes" ON public.invitation_codes
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- 인증된 사용자는 자신이 사용한 코드만 볼 수 있도록 허용
CREATE POLICY "Allow authenticated users to read their used code" ON public.invitation_codes
    FOR SELECT
    USING (auth.uid() = used_by);